- name: Undeploy cartridge with cmu
  hosts: '{{ SubscriptionID }}'
  gather_facts: False
  remote_user: root
  
  tasks:
    - name : Get the hostname
      shell: hostname
      register: hostname

    - name : Undeploy cartridge
      shell: ~/undeploy.sh {{ hostname.stdout }}
      delegate_to: cmu

    - name : Unregister this server from ansible
      shell: ~/ansible/manage_ansibleHosts.py remove {{ SubscriptionID }} {{ inventory_hostname }}
      delegate_to: localhost

    - name : Unregister this server from CMDB
      shell: ~/ansible/manage_3tiers_data.py remove "{{ SubscriptionID | regex_replace('web-','') }}" web {{ inventory_hostname }}
      delegate_to: localhost
