- name: Install database software
  hosts: "{{ SubscriptionID }}"
  gather_facts: False
  remote_user: root
  
  vars: 
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
  
  tasks:
    - name: remove target host old servers identities from local known_hosts list
      shell: ssh-keygen -R  {{ item }}
      with_items:
        - "{{ inventory_hostname }}"
      delegate_to: localhost
       
    - name: get target host current fingerprint
      shell: ssh-keyscan {{ hash_option | default("")}} {{ inventory_hostname }} >> {{ known_hosts_file }}
      delegate_to: localhost

    - name: Install Epel repo
      shell: rpm -q epel-release || rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
      retries: 2
      delay: 2

    - name: Install unzip
      yum: name=unzip state=present 

    - name: Install ntpdate
      yum: name=ntpdate state=present 

    - name: Install php
      yum: name=php state=present

    - name: Install mysql-server
      yum: name=mysql-server state=present

    - name: Install mysql-client
      yum: name=mysql state=present
    
    - name: Install python-mysqldb required by ansible mysql module
      yum: name=MySQL-python state=present

    - name: Install libselinux-python required by ansible copy module
      yum: name=libselinux-python state=present

    - name: Install php-mysql
      yum: name=php-mysql state=present

    - name: Install libgd
      yum: name=gd state=present

    - name: Install php-gd
      yum: name=php-gd state=present

    - name: Install php5-mcrypt
      yum: name=mcrypt state=present

    - name: Install php-mcrypt
      yum: name=php-mcrypt state=present

#    - name: Install php-db
#      yum: name=php-db state=present

    - name: Install phpmyadmin
      yum: name=phpmyadmin state=present
    
    - name: Restart mysql
      service: name=mysqld state=started

    - name: Create DB admin user remote
      mysql_user: name=prestashop password=prestashop1234 priv=*.*:ALL,GRANT host='%' state=present

    - name: Create DB admin user local
      mysql_user: name=prestashop password=prestashop1234 priv=*.*:ALL,GRANT host='localhost' state=present

    - name: Create wordpress DB admin user remote
      mysql_user: name=wordpress password=wordpress1234 priv=*.*:ALL,GRANT host='%' state=present

    - name: Create wordpress DB admin user local
      mysql_user: name=wordpress password=wordpress1234 priv=*.*:ALL,GRANT host='localhost' state=present

#    - name: Remove previous db if already exist
#      mysql_db: name=prestashop state=absent
#      
#    - name: Setup DB
#      mysql_db: name=prestashop state=present

#    - name: Copy dump to /tmp
#      copy: src=packages/dump.sql dest=/tmp/dump.sql owner=root group=root mode=0644
    
#    - name: Import DB dump
#      mysql_db: name=prestashop state=import target=/tmp/dump.sql

#    - name: Restart mysql
#      service: name=mysqld state=restarted

#    - name : Allow DB to listen on 0.0.0.0
#      replace: dest=/etc/mysql/my.cnf regexp='bind-address\s+=\s+127\.0\.0\.1' replace='bind-address = 0.0.0.0' backup=yes
#
#    - name: Restart mysql
#      service: name=mysql state=restarted
#
    - name: Allow mysql access step 1
      replace: dest=/etc/httpd/conf.d/phpMyAdmin.conf regexp='Allow from 127.0.0.1' replace='Allow from all' backup=yes 

    - name: Allow mysql access step 2
      replace: dest=/etc/httpd/conf.d/phpMyAdmin.conf regexp='Deny from All' replace='' backup=yes 

    - name: Restart apache
      service: name=httpd state=restarted
