- name: Configure interface for db virtual servers
  hosts: '{{ SubscriptionID }}'
  gather_facts: False
  remote_user: root

  vars: 
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
  
  tasks:

    - name: remove target host old servers identities from local known_hosts list
      shell: ssh-keygen -R  {{ item }}
      with_items:
        - "{{ inventory_hostname }}"
      delegate_to: localhost
       
    - name: get target host current fingerprint
      shell: ssh-keyscan {{ hash_option | default("")}} {{ inventory_hostname }} >> {{ known_hosts_file }}
      delegate_to: localhost
  
    - name : Add static route to 192.168.0.0
      shell: ip route add 192.168.0.0/16 via {{ ipaddressclient | regex_replace('(192.168.\d+).\d+','\\1.1') }}

    - name : Register this server client IP into CMDB
      shell: ~/ansible/manage_3tiers_data.py add "{{ SubscriptionID | regex_replace('database1-','') }}" database1-client {{ ipaddressclient }}
      delegate_to: localhost

    - name: Open firewall for mysql
      lineinfile: dest=/etc/sysconfig/iptables regexp="--dport 3390 -j ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 3390 -j ACCEPT" insertbefore="-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"

    - name: Open firewall for http
      lineinfile: dest=/etc/sysconfig/iptables regexp="--dport 80 -j ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT" insertbefore="-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"

    - name: Restart firewall
      service: name=iptables state=restarted
