- name: Find IP based on mac
  hosts: cmu
  gather_facts: False
  remote_user: root
 
  vars:

  tasks:

    - name: Probe backend network subnet
      shell: nmap -n -T5 -sP 192.168.21-23.0/24 ; arp -an | grep -i "{{ macaddressclient }}"
      delegate_to: localhost
      register: result
      delegate_to: localhost
      until: result.rc == 0
      retries: 30
      delay: 20

    - name: Probe mgmt network subnet
      shell: nmap -n -T5 -sP 10.3.8.0/24
      delegate_to: localhost

    - name: Get client IP from mac
      shell: arp -an | grep -i {{ macaddressclient }} | awk -F '(' '{ print $2 }' | awk -F ')' '{ print $1 }'
      delegate_to: localhost
      register: ipaddressClient

    - name: Get mgmt IP from mac
      shell: arp -an | grep -i {{ mgmtmacaddress }} | awk -F '(' '{ print $2 }' | awk -F ')' '{ print $1 }'
      delegate_to: localhost
      register: mgmtipaddress

    - name : Register this server mgmt IP into CMDB
      shell: ~/ansible/manage_3tiers_data.py add "{{ SubscriptionID }}" database1 {{ mgmtipaddress.stdout }}
      delegate_to: localhost

    - name : Register this server client IP into CMDB
      shell: ~/ansible/manage_3tiers_data.py add "{{ SubscriptionID }}" database1-client {{ ipaddressClient.stdout }}
      delegate_to: localhost

    - name : Output client ipaddress
      debug: msg="ipaddressClient = {{ ipaddressClient.stdout }}"
      delegate_to: localhost

    - name : Output mgmt ipaddress
      debug: msg="mgmtipaddress = {{ mgmtipaddress.stdout }}"
      delegate_to: localhost
