- name: Configure Haproxy
  hosts: "{{ SubscriptionID }}"
  gather_facts: False
  remote_user: root
  
  vars: 
  
  tasks:
    - name: Wait for information to be provided
      wait_for: path={{ SubscriptionID  | regex_replace('haproxy-','') }}_web-client.flg
      delegate_to: localhost
    
    - name: Remove flag
      shell: rm {{ SubscriptionID  | regex_replace('haproxy-','') }}_web-client.flg
      delegate_to: localhost

    - name: Get web client ip
      shell: ./manage_3tiers_data.py get {{ SubscriptionID  | regex_replace('haproxy-','') }} web-client ip
      register: ip_webclient
      delegate_to: localhost

    - name: Configure haproxy
      template: src=templates/haproxy.cfg dest=/etc/haproxy/haproxy.cfg

    - name: Start haproxy
      service: name=haproxy state=started

    - name: Open firewall
      lineinfile: dest=/etc/sysconfig/iptables regexp="--dport 5000 -j ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 5000 -j ACCEPT" insertbefore="-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"

    - name: Restart firewall
      service: name=iptables state=restarted
