- name: Configure Haproxy
  hosts: "{{ SubscriptionID }}"
  gather_facts: False
  remote_user: root
  
  vars:
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"

  
  tasks:
    - name: remove target host old servers identities from local known_hosts list
      shell: ssh-keygen -R  {{ item }}
      with_items:
        - "{{ inventory_hostname }}"
      delegate_to: localhost

    - name: get target host current fingerprint
      shell: ssh-keyscan {{ hash_option | default("")}} {{ inventory_hostname }} >> {{ known_hosts_file }}
      delegate_to: localhost

    - name: Install haproxy
      yum: name=haproxy state=present
