- name: Configure prestashop
  hosts: "{{ SubscriptionID }}"
  gather_facts: False
  remote_user: root
  
  vars: 
  
  tasks:
    - name: Get db client ip
      shell: ./manage_3tiers_data.py get {{ SubscriptionID  | regex_replace('web1-','') }} database1-client ip
      register: ip_dbclient
      delegate_to: localhost
 
    - name: Update settings.conf
      replace: dest=/var/www/html/prestashop/config/settings.inc.php regexp='192.168.23.103' replace='{{ ip_dbclient.stdout }}' backup=yes



#    - name: Copy dump to /tmp
#      copy: src=packages/dump.sql dest=/tmp/dump.sql owner=root group=root mode=0644
#    
#    - name: Import DB dump
#      mysql_db: name=prestashop state=import target=/tmp/dump.sql
#
#    - name: Restart mysql
#      service: name=mysqld state=restarted
#
