- hosts: all
  sudo: true
  sudo_user: root

  roles:
  - role: dresden-weekly.network-interfaces
    network_manage_devices: yes
    network_interfaces:
    - device: eth0
      auto: true
      family: inet
      method: static
      address: 192.168.1.11
      network: 192.168.1.0
      netmask: 193.168.1.255
      gateway: 192.168.1.1
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
      subnets:
      - 192.168.1.12/32
    - device: eth1
      auto: true
      family: inet
      method: dhcp
