- name: Configure interface for web servers
  hosts: '{{ SubscriptionID }}'
  gather_facts: False
  remote_user: root

  vars: 
    - home_dir: "~"
    - known_hosts_file: "{{ home_dir }}/.ssh/known_hosts"
  
  tasks:

    - name: remove target host old servers identities from local known_hosts list
      shell: ssh-keygen -R  {{ item }}
      with_items:
        - "{{ inventory_hostname }}"
      delegate_to: localhost
       
    - name: get target host current fingerprint
      shell: ssh-keyscan {{ hash_option | default("")}} {{ inventory_hostname }} >> {{ known_hosts_file }}
      delegate_to: localhost
  
    - name : Install vlan
      apt: name=vlan state=present

    - name : Add 802.1q module
      shell: lsmod | grep "8021q" || modprobe 8021q 

    - name : Remove interface if already available
      shell: ip link | grep "eth0.{{ vlan }}" && ip link delete eth0.{{ vlan }}; echo "Interface removed"

    - name : Configure vlan
      shell: vconfig add eth0 {{ vlan }}

    - name : Rename interface
      shell: ip link set $(ip link | grep rename | awk '{print $2'} | awk -F '@' '{print $1}') name eth0.{{ vlan }}

    - name : Get ip via dhcp
      shell: dhclient eth0.{{ vlan }}

    - name : Add static route to 10.3.0.0/16
      shell: ip route | grep "10.3.0.0/16" || ( ip route delete 10.3.8.0/24 && ip route add 10.3.0.0/16 dev eth0 )

    - name : Set default route to client subnet
      shell: ip route replace default via $(ip a show dev eth0.{{ vlan }}  | grep "inet " | awk '{print $2}' | awk -F '/' '{print $1}' | sed 's/\s//g' | sed 's/\.[0-9]\+$/.1/')

    - name : Get mac@
      shell: ip addr show dev eth0.2251 | grep "link/ether" | awk '{print $2}'
      register: macaddress

    - name : Get ip@
      shell: ip addr show dev eth0.2251 | grep "inet " | awk '{print $2}' | awk -F '/' '{print $1}'
      register: ipaddress

    - name : Get hostname
      shell: hostname
      register: hostname

    - name : Register this server into CMDB
      shell: ~/ansible/manage_3tiers_data.py add "{{ SubscriptionID | regex_replace('web-','') }}" web-client {{ ipaddress.stdout }}
      delegate_to: localhost

    - name : Output mac@
      debug: msg="Mac address client[{{ inventory_hostname }}]={{ macaddress.stdout }}"

    - name : Output ip@
      debug: msg="ip address client[{{ inventory_hostname }}]={{ ipaddress.stdout }}"

    - name : Output hostname@
      debug: msg="hostname[{{ inventory_hostname }}]={{ hostname.stdout }}"
